name: meflisy_service
description: A new Flutter application.

version: 7.0.0+14

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intro_views_flutter: '^2.4.0'
  shared_preferences: ^0.5.3+4
  flutter_launcher_icons: "^0.7.2"
  firebase_auth: ^0.14.0
  pinput: ^0.1.10
  connectivity: ^0.4.4
  http: ^0.12.0+2
  dio: ^2.1.13
  auto_size_text: ^2.1.0
  image_picker: ^0.6.1+4
  permission_handler: ^3.1.0
  image_cropper: ^1.0.2
  flutter_image_compress: ^0.6.0
  razorpay_flutter: ^1.1.1
  fluttertoast: ^3.1.3
  intl: ^0.16.0
  url_launcher: ^5.1.2
  get_it: ^1.0.3+2
  carousel_slider: ^1.3.1
  carousel_pro: ^1.0.0
  gradient_app_bar: ^0.0.1
  smooth_star_rating: ^1.0.3
  shimmer: ^1.0.1
  flare_flutter: ^1.5.9
  share: ^0.5.2
  flutter_spinkit: ^4.1.0
  cached_network_image: ^2.0.0
  firebase_messaging: ^6.0.9
  firebase_remote_config: ^0.3.0+1
  package_info: ^0.4.0+13
  flutter_platform_widgets: ^0.30.1
  ff_navigation_bar: ^0.1.3
  flutter_circular_chart: ^0.1.0
  pie_chart: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/meflisyicon.png"

flutter:
  uses-material-design: true


  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

  assets:
    - images/splash.png
    - images/company.png
    - images/meflisyicon.png
    - images/meflogin.png
    - images/splashPartner.png
    - images/edit.png
    - images/partnerBackground.png
    - images/paymenbackground.png
    - images/WhatsApp.png
    - images/advertise.png
    - images/franchisecard.png
    - images/advertismenlogo.png
    - images/franchisescreen.png
    - images/advertiseexample.png
    - images/splch screen.gif
    - images/nothinfound.png
    - images/walletlogo.png
    - images/icon.png

